/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.6.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Binary = string;
export interface InstantiateMsg {
  oracle_key_type: string;
  oracle_pubkey: Binary;
}
export type ExecuteMsg = {
  transfer: {
    amount: Uint128;
    recipient: string;
  };
} | {
  send: {
    recipient: string;
  };
} | {
  oracle_data_update: {
    data: OracleDataEntry[];
    signature: Binary;
  };
} | {
  update_oracle: {
    new_key_type?: string | null;
    new_pubkey: Binary;
  };
};
export type Uint128 = string;
export interface OracleDataEntry {
  reason: string;
  wallet: string;
  risk_score?: number;
}
export type QueryMsg = {
  get_oracle_data: {};
} | {
  get_oracle_pubkey: {};
} | {
  get_admin: {};
} | {
  get_balance: {
    address: string;
  };
} | {
  check_a_m_l: {
    wallet: string;
  };
};
export type Boolean = boolean;
export type Addr = string;
export interface AdminResponse {
  admin: Addr;
}
export interface OracleDataResponse {
  data: OracleDataEntry[];
}
export interface OraclePubkeyResponse {
  key_type: string;
  pubkey: Binary;
}