/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.6.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { Coin, StdFee } from "@cosmjs/amino";
import { Binary, InstantiateMsg, ExecuteMsg, Uint128, OracleDataEntry, QueryMsg, Boolean, Addr, AdminResponse, OracleDataResponse, OraclePubkeyResponse } from "./Oracle.types";
export interface OracleReadOnlyInterface {
  contractAddress: string;
  getOracleData: () => Promise<OracleDataResponse>;
  getOraclePubkey: () => Promise<OraclePubkeyResponse>;
  getAdmin: () => Promise<AdminResponse>;
  getBalance: ({
    address
  }: {
    address: string;
  }) => Promise<Uint128>;
  checkAML: ({
    wallet
  }: {
    wallet: string;
  }) => Promise<Boolean>;
}
export class OracleQueryClient implements OracleReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;
  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.getOracleData = this.getOracleData.bind(this);
    this.getOraclePubkey = this.getOraclePubkey.bind(this);
    this.getAdmin = this.getAdmin.bind(this);
    this.getBalance = this.getBalance.bind(this);
    this.checkAML = this.checkAML.bind(this);
  }
  getOracleData = async (): Promise<OracleDataResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_oracle_data: {}
    });
  };
  getOraclePubkey = async (): Promise<OraclePubkeyResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_oracle_pubkey: {}
    });
  };
  getAdmin = async (): Promise<AdminResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_admin: {}
    });
  };
  getBalance = async ({
    address
  }: {
    address: string;
  }): Promise<Uint128> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_balance: {
        address
      }
    });
  };
  checkAML = async ({
    wallet
  }: {
    wallet: string;
  }): Promise<Boolean> => {
    return this.client.queryContractSmart(this.contractAddress, {
      check_a_m_l: {
        wallet
      }
    });
  };
}
export interface OracleInterface extends OracleReadOnlyInterface {
  contractAddress: string;
  sender: string;
  transfer: ({
    amount,
    recipient
  }: {
    amount: Uint128;
    recipient: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  send: ({
    recipient
  }: {
    recipient: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  oracleDataUpdate: ({
    data,
    signature
  }: {
    data: OracleDataEntry[];
    signature: Binary;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  updateOracle: ({
    newKeyType,
    newPubkey
  }: {
    newKeyType?: string;
    newPubkey: Binary;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
export class OracleClient extends OracleQueryClient implements OracleInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;
  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.transfer = this.transfer.bind(this);
    this.send = this.send.bind(this);
    this.oracleDataUpdate = this.oracleDataUpdate.bind(this);
    this.updateOracle = this.updateOracle.bind(this);
  }
  transfer = async ({
    amount,
    recipient
  }: {
    amount: Uint128;
    recipient: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      transfer: {
        amount,
        recipient
      }
    }, fee, memo, _funds);
  };
  send = async ({
    recipient
  }: {
    recipient: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      send: {
        recipient
      }
    }, fee, memo, _funds);
  };
  oracleDataUpdate = async ({
    data,
    signature
  }: {
    data: OracleDataEntry[];
    signature: Binary;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      oracle_data_update: {
        data,
        signature
      }
    }, fee, memo, _funds);
  };
  updateOracle = async ({
    newKeyType,
    newPubkey
  }: {
    newKeyType?: string;
    newPubkey: Binary;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_oracle: {
        new_key_type: newKeyType,
        new_pubkey: newPubkey
      }
    }, fee, memo, _funds);
  };
}
export type { OracleDataEntry, ExecuteMsg, QueryMsg };